import Head from "next/head";
import styles from "../styles/Home.module.css";

import ObjectList from "./components/objectList";
import UploadFile from "./components/uploadFile";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Minio Storage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>MinIO Storage</a>
        </h1>
        <UploadFile />
        <p className={styles.description}>
          <b>All stored images</b>
        </p>
        <ObjectList />
      </main>

      <footer className={styles.footer}>MinIO & Quarkus POC</footer>
    </div>
  );
}
