version: "3.1"
services:
  s3:
    image: minio/minio:RELEASE.2021-02-11T08-23-43Z
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: test_user
      MINIO_ROOT_PASSWORD: test_pass
    command: server /data
    volumes:
      - data1-1:/data1
volumes:
  data1-1:
